[package]
name = "rusdox-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rusdox = { path = ".." }

[[bin]]
name = "docx_open"
path = "fuzz_targets/docx_open.rs"
test = false
doc = false
bench = false

[[bin]]
name = "spec_parse"
path = "fuzz_targets/spec_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "visual_render"
path = "fuzz_targets/visual_render.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]

[profile.release]
debug = 1
